### ISSUE TITLE
Electron 7 error

### ISSUE THREAD

**Issue by aminya** [UziTech/hyperlink-hyperclick#142]
[Enter steps to reproduce:]

1. Build Atom with Electron 7.3.3
2. Open Atom

**Atom**: 1.56.0-dev-0a62c4723 x64
**Electron**: 7.3.3
**OS**: Microsoft Windows 10 Home
**Thrown From**: [hyperlink-hyperclick](https://github.com/UziTech/hyperlink-hyperclick) package 3.0.1

### Stack Trace

Failed to activate the hyperlink-hyperclick package

```js
At Invalid package C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\Atom Dev x64\resources\electron.asar

Error: Invalid package C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\Atom Dev x64\resources\electron.asar
    at createError (electron/js2c/asar.js:126:17)
    at Proxy.fs.readFileSync (electron/js2c/asar.js:545:27)
    at compileFileAtPath (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:11:148280)
    at Object.value [as .js] (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:11:150918)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:11:146720)
    at /packages/hyperlink-hyperclick/lib/main.js:3:15)
    at /packages/hyperlink-hyperclick/lib/main.js:172:3)
    at Module.get_Module._compile (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:68:18)
    at customRequire (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:1:736637)
    at requireModule (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:1120418)
    at Package.requireMainModule (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:11:3708008)
    at Package.activateNow (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:11:3695992)
    at ~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:11:3695770
    at Package.measure (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:11:3693348)
    at ~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:11:3695630
    at new Promise (<anonymous>)
    at Package.activate (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:11:3695573)
    at PackageManager.activatePackage (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:11:383171)
```

### Commands

```
     -0:31.3.0 typescript:activate (atom-workspace.workspace.scrollbars-visible-always)
     -0:23.7.0 application:add-project-folder (button.btn.btn-primary)
```

### Non-Core Packages

```
ascii-hex 0.2.0 
atom-alignment 0.13.0 
atom-bash 1.1.1 
atom-beautify 0.33.4 
atom-commander 0.12.2 
atom-console 0.4.6 
atom-ide-base 2.1.3 
atom-ide-console 0.0.2 
atom-ide-datatip 0.20.4 
atom-ide-debugger 0.0.3 
atom-ide-definitions 0.3.6 
atom-ide-hyperclick 1.0.4 
atom-ide-javascript 1.5.0 
atom-ide-julia 0.1.0 
atom-ide-markdown-service 1.6.0 
atom-ide-outline 1.15.2 
atom-ide-signature-help 0.13.0 
atom-ide-template 0.1.0 
atom-ide-template-js 0.1.0 
atom-ide-template-rust 0.1.0 
atom-ide-vue 1.4.3 
indent-detective 0.4.0 
atom-material-ui 2.1.3 
atom-matlab-editor 0.4.0 
atom-minify 0.8.0 
atom-reverser 3.0.4 
atom-terminal 0.8.0 
atom-typescript 14.1.2 
atomic-management 0.3.1 
atomizr 0.23.3 
auto-fold 0.4.0 
autocomplete 0.47.0 
autocomplete-bash-builtins 0.3.5 
autocomplete-clang 0.13.1 
autocomplete-cmake 0.3.1 
autocomplete-en-en 0.2.0 
autocomplete-paths 2.12.15 
build 0.70.0 
build-cmake 0.12.0 
build-npm-apm 0.12.0 
busy-signal 2.0.1 
clean-context-menu 0.3.2 
colorful-json 1.1.0 
cson-parser 0.1.0 
ctags-status 1.4.0 
docblock-python 0.19.1 
fast-eslint 4.15.0 
file-icons 2.1.46 
find-scroll-marker 0.1.3 
find-trailing-whitespace 0.1.0 
flow-ide 1.13.0 
fold-functions 0.11.0 
fold-lines 0.2.2 
font-viewer 1.0.5 
glow undefined 
hello_world-webpack 0.1.0 
hey-pane undefined 
highlight-selected 0.17.0 
Hydrogen 2.14.6 
hyperclick 0.1.5 
hyperlink-hyperclick 3.0.1 
ide-bash 1.0.11 
ide-c-cpp 0.1.0 
ide-clangd 0.4.0 
ide-css 0.3.5 
ide-json 0.2.1 
ide-powershell 0.1.0 
ide-python 1.7.0 
ide-rust 0.22.0-beta.3 
ide-typescript 0.9.1 
ide-yaml 0.7.0 
ide-yml 0.7.8-0 
ink 0.12.5 
intentions 1.1.5 
javascript-drag-import 0.1.13 
javascript-refactor 0.7.1 
json-converter 0.2.4 
julia-client 0.12.6 
juno-plus 0.12.2 
jupyter-notebook 0.0.10 
keyword-pair-matcher 0.2.1 
kite 0.195.0 
language-assembly 0.7.2 
language-autohotkey2 1.0.1 
language-batchfile 0.7.5 
language-cmake 1.2.0 
language-github-actions 0.1.0 
language-julia 0.20.1 
language-latex 1.2.0 
language-matlab 0.2.1 
language-matlab-octave 1.0.5 
language-matlab-plus 1.12.0 
language-powershell 5.0.0 
language-reg 0.0.0 
language-vue 0.26.0 
language-weave 0.7.2 
latex-autocomplete 1.1.1 
latex-completions 0.3.6 
latex-friend 0.0.11 
latex-image-paste 0.5.0 
latex-itemizer 1.1.1 
latex-tree 0.5.0 
latex-wordcount 0.6.0 
less-than-slash 0.19.0 
lint-scroll-marker 0.3.0 
linter 3.1.1 
linter-clang 4.1.2 
linter-coffeelint 2.0.65 
linter-cpplint 2.1.0 
linter-eslint 8.5.5 
linter-flake8 2.4.0 
linter-gcc 0.9.0 
linter-gcc2 0.8.8 
linter-julia 0.8.3 
linter-matlab 1.3.0 
linter-shellcheck 1.6.0 
linter-spell 0.15.0 
linter-spell-javascript 0.9.0 
linter-spell-latex 0.11.0 
linter-tslint 1.10.43 
linter-ui-default 2.2.1 
markdown-preview-plus 4.6.1 
markdown-writer 2.11.11 
menu-manager 0.6.0 
minimap 4.35.6 
minimap-autohider 1.7.0 
minimap-bookmarks 0.4.3 
minimap-codeglance 0.4.7 
minimap-find-and-replace 5.0.5 
minimap-highlight-selected 4.6.2 
minimap-lens 0.8.1 
minimap-linter 2.2.2 
minimap-plus 5.0.0 
minimap-selection 4.5.1 
minimap-titles 1.15.0 
multi-copy 0.1.0 
multi-cursor-plus 1.2.0 
multi-line-editor 1.6.0 
multi-paste2 0.4.1 
nuclide 0.390.0 
package-ts-generator 0.1.2 
pdf-view 0.72.0 
pigments 0.40.6 
preview 0.19.0 
preview-inline 1.5.1 
project-manager 3.3.8 
Quick-JavaScript 2.2.0 
script 3.26.0 
scroll-marker 0.3.5 
snippet-generator-plus 0.1.2 
snippets-plus 0.10.2 
split-diff 1.6.1 
string-encoder 0.2.0 
Sublime-Style-Column-Selection 1.7.5 
symbols-tree-nav 0.15.8 
sync-settings 5.1.0 
TabNine 3.0.1 
teletype 0.13.4 
terminal 0.0.0 
terminus 4.0.6 
tool-bar 1.3.0 
trailing-spaces 0.4.0 
tree-view-git-status 1.5.3 
turbo-javascript 1.4.0 
uber-juno 0.3.0 
vim-mode-plus 1.36.4 
web-view 3.0.0 
x-terminal 12.0.4 
```

**Comment by UziTech** [comment]
This should be fixed in v3.0.2
